### ISSUE TITLE
Cookie header too big error

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-embed#1005]
When viewing stanford-only items in sul-embed, if you scroll through a very long thumbnail list, eventually all requests to stacks will error out because the `Cookie` header is too big.

**Comment by cbeer** [comment]
Fixed by updating the servers to to shibboleth 3.0.4

**Comment by thatbudakguy** [comment]
I'm seeing this fairly consistently right now in firefox, and it doesn't appear to be related to repeated requests (could be a different issue, but not sure).

This is visible in two ways. The first:
1. load, for example, https://purl.stanford.edu/fr352bj3947
2. several initial requests (5) get made to IIIF image endpoints, e.g. https://stacks.stanford.edu/image/iiif/fr352bj3947/fr352bj3947_00_0004/full/157,/0/default.jpg
3. all 5 requests fail with a 400 bad request; the server responds "Your browser sent a request that this server could not understand. Size of a request header field exceeds server limit."
4. check headers and see that the cookie is gigantic; there are many (100+) fields with names like `_shibstate_1655850383_70ef`.

The second:
1. load, for example, https://purl.stanford.edu/fr352bj3947
2. attempt to authenticate by clicking "continue"; request is made to https://stacks.stanford.edu/auth/iiif?origin=https://embed.stanford.edu
3. authentication immediately fails; popup window displays server's "Your browser sent a request that this server could not understand. Size of a request header field exceeds server limit." response
4. check headers and see the the same results as above

In one instance, checking the cookie actually showed a raw `[object Object]` JavaScript value instead of the cookie itself, and the browser seemed to be having trouble parsing the cookie. Not sure what happened there.

**Comment by thatbudakguy** [comment]
was able to fix this by doing an SSO logout (https://login.stanford.edu/idp/profile/Logout) and then re-authenticating, so...closing, I guess. not sure how a problematic cookie was still generated after the shibboleth update?

**Comment by jcoyne** [comment]
I'm unable to duplicate this.
