### ISSUE TITLE
Access to downloads and labeling for "window options"

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-embed#1082]
Feedback from Ben Stone:

> I've noticed that a number of users, both internal and external have had some challenges figuring out how to download images. While the old image viewer had an icon with a downward facing arrow, the new viewer's three vertical dots (with the roll over message for "window options") sometimes is missed by users who are looking for a simple download button or icon.   Is there any way we could better name or illustrate this feature?  I understand that the window options button is designed to both enable users to share and download (and once they click on it, they do see the clearly labeled download feature); while it might add clutter to the bar, perhaps breaking out the  share and download features with their separate icons could be possible?
>
> Happy to discuss further and thanks for this great new image viewer!

Things to do/consider:

* What are our options?
* Should we add buttons to the toolbar? If so, what are the implications on our instance of Mirador 3 vs. upstream?
* Would it be adequate to change the icon/label for this? (A possible but not necessarily good option: `More actions`)

I'd like to get back to Ben by the end of the October with a proposed resolution, so it'd be good to get some movement on this soon.

**Comment by anarchivist** [comment]
See also Kris's feedback on #1083:

> I'm having a hard time finding how to download the pdfs from the viewer (checking to see if the pdf will download is part of the QA checklist) - after looking at 15 objects, and by pure whim, I discovered that the three dots in a line contains the download option. But then it appears I cannot download the entire pdf? Just one page at a time? Is there another way to do this?

**Comment by jvine** [comment]
Immediate issue:  Make the download/share menu more discoverable. Broader issue: We can't seem to avoid the need for small specialized menus _and_ a general "more things" menu. We need to continue to be cautious about the proliferation of toolbar buttons, and better manage those buttons in small windows. 

## Make the download/share menu more discoverable

Split the menu out from the shared "dot" menu, in the same way we did with the display menu. 
- [ ] Separate the Download and Share options into their own menu
- [ ] Locate the menu immediately after the Display menu
- [ ] Add icon
- [ ] Tooltip is "Download & share"

So in current sul-embed, we will have 3 window toolbar buttons:
<img width="201" alt="3icons" src="https://user-images.githubusercontent.com/6945691/67605610-b4c96100-f733-11e9-97ca-87b0e2b41c54.png">

We will continue to use the dot menu for additional features (like Image manipulation, for example) as they are introduced. 
<img width="218" alt="4icons" src="https://user-images.githubusercontent.com/6945691/67605571-8a77a380-f733-11e9-8ec7-e9a72983df21.png">
The dot menu will likely need to be renamed as well. The current name is to help differentiate it from the "Workspace options" menu on the Mirador sidebar, but since that doesn't exist in embed, it's not a useful distinction. It might be enough to label it "More..."

### Download/share icon

The only examples I've found of combined Download/Share menus use horizontal or vertical dots. So. We can either prioritize one of the actions, and use that icon alone; or we can use a custom hybrid icon. I prefer the custom but am open to other opinions.

| download | share | custom |
| -- | -- | -- |
| <img width="23" alt="download" src="https://user-images.githubusercontent.com/6945691/67605221-957e0400-f732-11e9-939b-f8e75929abb7.png"> | <img width="26" alt="share" src="https://user-images.githubusercontent.com/6945691/67605220-957e0400-f732-11e9-8dce-4d9727848382.png"> | <img width="26" alt="custom" src="https://user-images.githubusercontent.com/6945691/67605223-957e0400-f732-11e9-9e34-1906cf072ba9.png"> | 

[many other share icons, there's no clear standard](https://www.fastcompany.com/3031872/why-isnt-there-a-standard-share-button)

**Custom svg**
```
<svg role="presentation" aria-hidden="true" viewBox="0 0 24 24" focusable="false" class="MuiSvgIcon-root">
  <path d="M0,0H24V24H0Z" fill="none"></path>
  <path d="M19,12v7H5V12H3v9H21V12Z"></path>
  <path d="M11.741,8.178V5L17.3,10.562l-5.562,5.562V12.867c-3.973,0-6.754,1.271-8.741,4.052C3.795,12.946,6.178,8.973,11.741,8.178Z" transform="translate(4 -4)"></path></svg>
```

## Handling multiple toolbar buttons in a small window

Problem: In very small windows (e.g. multi-up comparison) we currently collapse the title until it disappears, then start clipping icons from the right. The functionality from those clipped icons is not available to the user unless the window is expanded, which they may not know/want to do.

Design issue for Mirador 3.

**Comment by anarchivist** [comment]
Thanks, @jvine - could you write up a quick email summary of our nearer term potential fix to share with stakeholders? 

I'm guessing that this fix is pretty small and can fit in a maintenance work cycle, but if there are specific challenges or concerns, please let me know.
