### ISSUE TITLE
Issues with zoom level for very large (vertically-long) images 

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-embed#1097]
### Expected behavior

I should be able to zoom into large images across supported browsers (e.g. contemporary versions of Chrome, Firefox, and Safari). This specifically impacts piano rolls: 
 
https://purl.stanford.edu/xq762nt7491
https://purl.stanford.edu/rt595wj4442

#### Chrome

Works fine, as far as I can tell. Yay!

#### Firefox 

Image disappears within Mirador after the first few zoom levels. 

![m3-pianorolls](https://user-images.githubusercontent.com/73732/71105829-0827c080-2173-11ea-93df-9107c5a84068.gif)

#### Safari

Past the first few zoom levels, CPU and RAM usage shoots up, and the viewer/browser tab becomes less responsive to actions. Eventually, Safari displays a notification that the page is using lots of RAM.

![m3-pianorolls-safari](https://user-images.githubusercontent.com/73732/71105958-49b86b80-2173-11ea-8bbd-843627991e43.gif)

### Steps to reproduce the behavior

View one of the following objects in Firefox or Safari:

https://purl.stanford.edu/xq762nt7491
https://purl.stanford.edu/rt595wj4442

### Browser / Environment

macOS 10.14.6; Firefox 70.0.1 and 71.0; Safari 13.0.4

**Comment by mejackreed** [comment]
Potentially related historical issue https://github.com/sul-dlss/sul-embed/issues/900

**Comment by mejackreed** [comment]
Again related to https://github.com/openseadragon/openseadragon/issues/381#issuecomment-229989794

It seems that issue here is the following:
OpenSeadragon adds images to an offscreen canvas. This breaks at different size maxes which are different in every browser.

 At zoom level 3, OpenSeadragon will request https://stacks.stanford.edu/image/iiif/xq762nt7491%252Fxq762nt7491_0001/full/512,/0/default.jpg

which is 512 x 48915 = 25043968 pixels

I wonder if we can set a max tileSize height in Cantaloupe? https://stacks.stanford.edu/image/iiif/xq762nt7491%2Fxq762nt7491_0001/info.json
Confirmed offscreen canvas is the issue by rendering the image with Mirador 3 using `useCanvas: false`.

I can't
