### ISSUE TITLE
CDL: Translate loan periods >24 hours to accurately display due date/time

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/sul-embed#1216]
- [x] When not checked out, translate the loan period to " x day" or "x week" loans.  (e.g. 24-hour = "1 day", 168-hour = "1 week")

- [ ] When item is checked out, include the date the item is due (in addition to the time).  This needs to display to the user that has the item checked out AND anyone joining the waitlist.

Current view when item not checked out:
![image](https://user-images.githubusercontent.com/14897546/96925063-72cb1c00-1468-11eb-9a7e-84c0f0870b08.png)

Current view for user with item checked out.  Missing is the information that this is due 1 week from today at 1:15pm PDT:
![image](https://user-images.githubusercontent.com/14897546/96926206-1ff26400-146a-11eb-952f-f0002ac43420.png)

Current view for others when item is checked out.  Again, missing is that the item is due in 1 week at 1:15pm PDT:
![image](https://user-images.githubusercontent.com/14897546/96926583-998a5200-146a-11eb-9650-a7b2b8e7660e.png)

 
Example record in Prod: http://purl.stanford.edu/cy779fp8559

**Comment by cbeer** [comment]
@saseestone / @ggeisler : do you want to give us some guidance about date formats, and when + how to round to days vs weeks (like, I'm guessing 10 days makes more sense than 1.42 weeks..... )

**Comment by ggeisler** [comment]
@cbeer Below are suggestions @saseestone and I came up with for the different potential cases. Let me know if this doesn't cover all the questions you had. (We're not sure your rounding question comes into play since the two main cases are displaying a fixed loan period or a specific date/time value.)

### Not checked out
There are (if I understand correctly) four possible loan periods. These should be represented with a hyphen like so:

<img width="469" alt="Screen Shot 2020-11-02 at 2 25 24 PM" src="https://user-images.githubusercontent.com/101482/97921476-3cb75300-1d18-11eb-8332-73c52a158e16.png">

So the possible values ares:

`2-hour`
`4-hour`
`2-day`
`1-week`

### User has item checked out
Here we're adding the date and modifying the string with some punctuation (mockup below doesn't have the correct icon or background color for a checked out item because I don't know how to easily get that type of example; the string is the only thing I'm mocking up):

<img width="358" alt="Screen Shot 2020-11-02 at 2 25 11 PM" src="https://user-images.githubusercontent.com/101482/97921855-c8c97a80-1d18-11eb-9e66-9e28d306dd43.png">

Changes from current are:

- Add date using `mm/dd/yyyy` format
- Add `at` between date and time
- Adjust time format to add space between numbers and the `a.m.` part
- Add periods for `a.m.` and `p.m.`
- Drop the leading zero for hours (e.g., `1:15 p.m.` instead of the`01:15pm` in the original comment examples

### Checked out by someone else
The same as the case above but adding `Checked out.` (with a period that is not currently present) before `Due...`

<img width="446" alt="Screen Shot 2020-11-02 at 2 24 45 PM" src="https://user-images.githubusercontent.com/101482/97923072-a89abb00-1d1a-11eb-8d9a-1339de4e826a.png">

### Due less than 24 hours from now
For the two cases where we display the "Due" date/time value, if the due date is less than 24 hours from the current time, substitute `Tomorrow` for the date part:

<img width="294" alt="Screen Shot 2020-11-02 at 2 58 29 PM" src="https://user-images.githubusercontent.com/101482/97923823-e51ae680-1d1b-11eb-927a-3dcbe4419fa4.png">

**Comment by cbeer** [comment]
My question about rounding was to save us any future pain if other loan periods are added. Those are the values we have now, but this app doesn't restrict the values so....

**Comment by saseestone** [comment]
@cbeer good point about the lack of restriction in the values.  Is it possible to code a pattern like:

- Under 23 hours => "x-hour loan"
- Over 23 hours; under 167 hours => "x-day loan" (and I'll work to ensure that all ItemCat3s correspond to a day value)
- Over 167 hours; under 719 hours => "x-week loan" (again, with me working to ensure that we correspond to a week value.  So your example of a 10 day loan just wouldn't happen. It would either be a "1-week loan" or a "2-week loan")
