### ISSUE TITLE
Add keyboard navigation to image viewer views

### ISSUE THREAD

**Issue by jchristo4** [sul-dlss/sul-embed#143]

**Comment by aeschylus** [comment]
There are several meanings for the same keys depending on context. We should also provide a way to traverse these contexts. See https://github.com/madrobby/keymaster#scopes. The below describes the behaviour within contexts. The last section describes how to navigate _between_ contexts.
 
## Opening Context (main toolbar, thumbnail view)
`tab` to enter thumbnail pane through the tab ring including all controls. Must also loop through the pages.
`down`, `right`, `left`, `up` select different thumbnails (same as hovering with the mouse)
`enter` zooms into the selected page (note that page selection can be controlled from the keyboard, this has implementation implications: the currently focused item must be [held as data](http://nicolashery.com/describing-ui-state-with-data/) somewhere). Left and right are easy to define because we are using an array to model the page sequence, but what about up and down? This requires an understanding of the relative spatial position of the images in two dimensions. 
`m` cycles through viewing modes (book or single page, could be extended to include top-to-bottom, scroll, continuous, etc). When there are more modes, there could also be dedicated keys for specific modes.
`shift + down` zooms into the current page, whether or not it is deliberately focused. This is useful when the user has just zoomed out for context, but wants to go back to where they just were.

## Within Focused (Zoomed-in) View
`down`, `right`, `left`, `up` "bumps" or pans in the respective direction. Pressing `left` or `right` a second time after releasing it when the user has already reached the extent of the canvas will go to the next or previous page depending on reading direction. Holding down a panning key should accelerate the panning until the release of the key.
`enter` zooms down a level, `shift+enter` zooms up a level. Holding the keys zooms in or out more slowly.
`shift+left` and `shit+right` advance to the next or previous page depending on reading direction. The canvas zooms out to the page level as it does so. Optionally, the initial zoom level of a new opening in book mode can be zoomed in to the top of the recto page for easy reading.
`shift+up` zooms out to thumbnail mode at the correct scroll position with the current page clearly marked
`m` cycles through viewing modes

## Navigating between contexts
At any time, for accessibility reasons, it must be necessary to navigate using the `tab` key. Elements are placed in the tab ring in descending order, with the highest elements in the hierarchy first, then cycling through sibling children and their children in a _depth-first_ manner.

To deliberately traverse the levels of the hierarchy, the user may press `shift+up` at any time to reset their place in the tab ring. They may then tab within that context, or use `shift+right/left/up/down` to select items spatially in a _breadth-first_ manner. Pressing `enter` then resents their control scope to that of the selected element.

**Comment by mejackreed** [comment]
Tagging @jvine for comment

**Comment by jvine** [comment]
I'm not sure if I'm reading the last section correctly. I think the accessible pattern would be: `tab` to major elements; arrow-key navigation within the element; `enter` to activate; `shift-tab` to back out of the element. 

It might be worth reviewing this outline with the WebAIM discussion list (http://webaim.org/discussion/) or some other actual keyboard nav expert.

**Comment by aeschylus** [comment]
I have joined their mailing list and will hopefully hear back from them soon about the proposed controls. Since I was mostly planning on implementing those "power user" controls in javascript without marking elements (but to do so without interfering with assistive devices), I doubt they will be very receptive.

The last paragraph has to do with moving hierarchically through the interface modules. It's been about 2 years since I actually read the wai-aria specification or related, but I thought that tab moves linearly through a list of elements in an order of the assistive technology's choosing, and that these can be marked with a tab-index attribute if needed. The last paragraph is about users who prefer to use the keyboard, rather than those who must use the keyboard. So rather than moving linearly back and forth through a long list of elements, elements that are visual parents can be immediately selected, and children can be selected using the four direction arrow keys. This would mean that a thumbnail that was above the currently accursed thumbnail could be accessed with an up arrow key, and a thumbnail to the right could be accessed with the right arrow key, similar to how the cursor of this text editor can move between lines or between letters of the same line. This would provide visual and hierarchical navigation of the DOM using the keyboard, similar to the way text is navigated. 

Whatever is implemented [keymaster]( https://github.com/madrobby/keymaster) will make it significantly easier and more cross-browser compliant.
