### ISSUE TITLE
virtex3d is unmaintained

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1486]
We should switch to something that is maintained. 

After some prototyping and experimentation (see below) and consultation with @calavano and @andrewjbtw we can move forward using [model-viewer](https://modelviewer.dev/). We are not going to modify assemblyWF at this time, and will migrate the existing OBJ files to GLB (GLTF), and update them.

Maybe these should be separate tickets but it seems easier just to list the sub-tasks here:

- [x] Download existing 3D items that accessioned from preservation-catalog
- [x] Convert the OBJ files to GLB (GLTF)
- [ ] Accession the new files
- [x] Update sul-embed to use model-viewer instead of virtex3d
- [ ] Is keyboard-only navigation is possible for zoom in/out?
- [ ] Does model-viewer support full descriptions for stage views in place of "viewing stage left", etc? If it does, could additional metadata be supplied during accessioning?

**Comment by edsu** [comment]
Not knowing much about the 3D objects in SDR I was curious about the file formats we are displaying with virtex3d.

I used Argo to generate a [report](https://argo.stanford.edu/catalog?f%5Bcontent_type_ssim%5D%5B%5D=3d) for all items that have content type "3D". I exported the metadata for the 446 items as a CSV. 130 of these have zero files, and were never released (e.g. [cd935cv6455](https://argo.stanford.edu/view/druid:cd935cv6455), which leaves 316 items.

I fetched the Cocina for the 316 and listed out the filenames in the structrual metadata, and then counted the number of file extensions:

| Extension | Count |
|:---|---:|
| obj | 315 |
| mtl | 315 |
| jpg | 243 |
| tar | 112 |
| zip | 100 |
| ply | 75 |
| stl | 1 |
| json | 1 |

So it looks like [obj](https://docs.fileformat.com/3d/obj/) and [mtl](https://docs.fileformat.com/3d/obj/) files are being used, and the Virtex viewer is initalized witht he `.obj` file URL.  It looks like virtex3d is mostly a shim around [three.js](https://github.com/mrdoob/three.js). 

It seems like we can:

1. Jettison virtex3d and use three.js directly (which is actively maintained, and supports many formats).
2. Look at converting our obj & mtl files to [gltf](https://docs.fileformat.com/3d/gltf/) and then using Google's model-viewer for rendering. It does seem like GLTF is the ascendant format for 3d? Incidentally model-viewer uses three internally, but doesn't provide an interface for the many file format loaders in three. It's not yet clear if we can do this conversion on demand or if we would need to accession the new files into SDR.

**Comment by edsu** [comment]
I'm going to proceed with doing some research for 2 (adding GLTF files for these objects). I'd like to create a comparison view of the objects we have, and let a curator take a look to see if there are any noticeable differences we should care about. Then I would like to come up with a plan for how to update them, if it does look like a viable way forward.

**Comment by edsu** [comment]
@thatbudakguy brought up the good point that based on how many 3D objects we might expect to be getting in the future we may want to consider creating GLTF derivatives during accessioning.

**Comment by edsu** [comment]
@andrewjbtw suggested I get in touch with @calavano to see what he thinks about the idea of converting our OBJ files to GLTF. He was open to the idea of exploring how viewing GLTF files compares with viewing OBJ files with vertex3d. He mentioned that the faculty member in Archaeology who was most active in depositing 3D scans is no longer at Stanford, but there is a new faculty member there who has expressed interest. Tony expects to see about 12 objects scanned per year from him.

I am going to proceed by creating a small static site that lets Tony (and others) inspect and compare both versions of world viewable 3d objects in SDR. 

Tony mentioned a few things that will be important to keep in mind:

- vertex3d was limited to viewing objects with 65k vertices. The [3d digitization workflow](https://docs.google.com/document/d/1K2GBtP-0-x87OSxKQIIo3ZI6w_u3qTp5GqDbyD0Aoy8/edit) instructs curators to create a downsampled obj file. It's possible that model-viewer is more capable of viewing the original? @edsilv (original developer of vertex3d) indicated to me that this came up in recent conversations about viewing GLB files in model-viewer and they work best when they are less than 10MB.
- it will be good to see how the neural maps work, which allow lower resolution objects to seem smoother. model-viewer may fix some defects related to this?
- it would be good to see if converting to GLTF (or GLB) can be done in AssemblyWF so that items that are submitted using the current digitization workflow will continue to work. It could potentially be done manually for a bit, but ideally installation of NodeJS and npm modules, and running something on the command line will *not* be something digitization lab people will need to do.
- we might want to think about users who self-deposit 3d objects and how they can be supported/guided.

**Comment by edsu** [comment]
@calavano has looked at the [before/after demo](https://sul-dlss-labs.github.io/3d-eval/) and has indicated that we can move forward using model-viewer. After consultation with @andrewjbtw we are not going to modify assemblyWF at this time, and will migrate the existing OBJ files to GLB (GLTF), and update them.

Maybe these should be separate tickets but it seems easier just to list the sub-tasks here:

- [ ] Download existing 3D items that accessioned from preservation-catalog
- [ ] Convert the OBJ files to GLB (GLTF)
- [ ] Accession the new files
- [ ] Update sul-embed to use model-viewer instead of virtex3d
