### ISSUE TITLE
Indicate Stanford-only access after authentication on media objects

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1531]
### Expected behavior
There should be an indicator that the media item requires authentication even after you have authenticated so you know that when you share this URL, the user on the other end may not have access.

### Actual behavior

Once you are logged in there is no indicator that you needed to log in to see this.

### Browser / Environment

See https://github.com/sul-dlss/media/issues/152

**Comment by alundgard** [comment]
- See the Access Banner Prototype in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design). [To launch the interactive prototype in Figma, click the "Present" play arrow in the top-right corner. From this tab, click Access Banner Prototype under the "Flows" panel.]
- The current design approach introduces an "authentication tab" as a persistent indicator.
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/84343596-bb3b-4ee1-9801-d92b6d9c09a6)
- Contact me for additional context and/or design revisions due to technical feasibility.

**Comment by mjgiarlo** [comment]
Simpler approach: a persistent banner across the tab (i.e., not collapsible). That is also fine.

**Comment by alundgard** [comment]
Here's a [Mirador example](https://purl.stanford.edu/bb627py6670) of the simpler approach (persistent banner across the top).
