### ISSUE TITLE
Poster should show for video with thumbnail

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1604]
This item has a thumbnail, so it should display as the poster: https://sul-purl-stage.stanford.edu/cm856pm4228

**Comment by hudajkhan** [comment]
Background:
The "poster" attribute is added if the resource file "thumbnail" method returns true:
https://github.com/sul-dlss/sul-embed/blob/main/app/components/embed/media_tag_component.rb#L81

The code looks for the following to ascertain if there is a thumbnail: 

- The resource element has a thumb attribute or has type (https://github.com/sul-dlss/sul-embed/blob/main/app/models/embed/purl/resource.rb#L30)
- Otherwise, if the resource  has a mimetype image (https://github.com/sul-dlss/sul-embed/blob/main/app/models/embed/purl/resource_file.rb#L86) and if the resource is one of the types defined in Settings which should have thumbnails (https://github.com/sul-dlss/sul-embed/blob/main/app/models/embed/purl/resource_file.rb#L62), then state that the resource has a thumbnail. These types are audio, file, and video.

**Comment by hudajkhan** [comment]
In this case, the resource with the file that has "role" set to thumbnail is of type "video", so it will return a thumbnail.  Right now, the poster attribute is being set on the video element: https://sul-stacks-stage.stanford.edu/image/iiif/cm856pm4228%2Fgt507vy5436_thumb/full/!800,600/0/default.jpg 

When I go to this URL, it says the image cannot be displayed as there has been an error.

**Comment by hudajkhan** [comment]
This error doesn't happen with some other requests that seem to be going beyond the original width (according to the info.json, it appears to be 960): https://sul-stacks-stage.stanford.edu/image/iiif/wm783fb6812%2Fgeneric_filename_FV4285_thumb/full/!7000,600/0/default.jpg

**Comment by hudajkhan** [comment]
Getting to the image server directly, requesting "iiif/2/cm%2F856%2Fpm%2F4228%2Fgt507vy5436_thumb.jp2/full/!641,600/0/default.jpg"  using gives the following error

"403 Forbidden

Requests for scales in excess of 100% are not allowed.

edu.illinois.library.cantaloupe.resource.ScaleRestrictedException: Requests for scales in excess of 100% are not allowed."

**Comment by hudajkhan** [comment]
A similar example in production:

https://stacks.stanford.edu/image/iiif/bb207gv9411%2Fbb207gv9411_SC0223_2005-170_b3_No_vacancy_thumb/full/!640,600/0/default.jpg dispays fine
but https://stacks.stanford.edu/image/iiif/bb207gv9411%2Fbb207gv9411_SC0223_2005-170_b3_No_vacancy_thumb/full/!640,600/0/default.jpg throws an error.  
PURL page: https://purl.stanford.edu/bb207gv9411
