### ISSUE TITLE
Accessability modal text depends on presence of transcript

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1705]
See the "Single Companion Window Desktop" prototype in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design
). [Click the "Present" play arrow in the top-right corner and select this prototype.]
<img width="473" alt="Screenshot 2023-11-08 at 8 58 49 AM" src="https://github.com/sul-dlss/sul-embed/assets/92044/3ae9ad4a-fb3c-44df-bc64-5c13eb09a492">

**Comment by mjgiarlo** [comment]
We would like a sample object in stage to test against. Andrew will point at examples of criteria (around determining if a transcript is available).

**Comment by andrewjbtw** [comment]
A couple of examples of how transcripts (PDF or TXT) have been accessioned along with media. These are more common than VTT captions because some oral history programs have been producing PDF transcripts for a long time. These are often edited versions that exist independently of the recordings and may not match it exactly.

- Item with a TXT transcript, where role has been set to Transcription: https://argo-stage.stanford.edu/view/druid:bk586kk6146
- Item with a PDF transcript, where no role has been set but the "resource label" is "Transcript": https://argo.stanford.edu/view/zd291sm2500
- Item with two PDF transcripts, where no role has been set but the "resource label" includes "Transcript": https://argo-stage.stanford.edu/view/druid:xb302rj8598

It might be feasible to go back and add the "Transcription" role to the PDF transcripts. That could have some downstream effect on IIIF manifests and contentsearch because I think the "Transcription" role was intended for indexable text in TXT/HTML/XML formats.

**Comment by aaron-collier** [comment]
@andrewjbtw it seems (based on my relative naive review of the code) that the most reliable way to determine IF there is a transcript would be if the role was present on any file in the object.

1.) Would remediating the data to add this role be doable in this work cycle? 
2.) How might we determine if the downstream effects are negative and could hold this work up?

Possible standup discussion tomorrow (or during retro when more of the team is available).

**Comment by mjgiarlo** [comment]
Before following up on this, we should finish #1744 to make it easier to test in stage.

**Comment by andrewjbtw** [comment]
I updated a sample media item to apply the role of transcription to a couple of PDF transcripts: https://sul-purl-stage.stanford.edu/xb302rj8598

I don't see any errors related to content search or anything else. That suggests that we can go ahead an reuse this role to indicate the presence of a transcript, even when a file is a PDF (and thus not something content search could index).

**Comment by mjgiarlo** [comment]
@andrewjbtw Great, thanks for testing! Does this issue need any updates or shall we move to ready? cc: @dinahhandel @jcoyne
