### ISSUE TITLE
Text search does not work in stage

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#1744]
To fully test the implications of setting file roles like "transcription" and to test the sul-embed viewer in general, we should have a working text search (contentsearch) in stage.

In terms of current media-specific work, this is related to the conversation on https://github.com/sul-dlss/sul-embed/issues/1705 about whether to use the role of "transcription" for PDF transcripts.

### Expected behavior
Text search in Mirador should work in stage the way it works in production.

### Actual behavior

Attempts to search in stage always result in an error shown in the viewer:

<img width="1268" alt="Screenshot 2023-11-14 at 11 42 49 AM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/d90e0be5-cb23-4d87-9b02-fed1c3ca4ed3">

An error shows up in HB as well - maybe it's in the configuration?:
> `HTTP::StateError: Persistence is enabled for https://stacks.stanford.edu, but we got https://sul-stacks-stage.stanford.edu`

https://app.honeybadger.io/projects/54556/faults/76092785

### Steps to reproduce the behavior

Go to https://sul-purl-stage.stanford.edu/zn167jj5855 and enter a search.

**Comment by hudajkhan** [comment]
The host needed to be specified explicitly in the shared configs for content search staging: https://github.com/sul-dlss/shared_configs/commit/027c5079deaa3145ce3ea3bcc92eec6c0ea3e49a

**Comment by hudajkhan** [comment]
Documenting where the error was occurring:
For reference, here is where the stacks host is defined in the content search repo: https://github.com/sul-dlss/content_search/blob/master/config/settings.yml#L11

The error is thrown in the fetch method here: https://github.com/sul-dlss/content_search/blob/master/app/models/purl_object/file.rb#L50 .  When the client tries to get the URL, it calls the code here https://github.com/sul-dlss/content_search/blob/master/app/models/purl_object/file.rb#L9 .

When the code requests "HTTP.persistent(Settings.stacks.host)", and sees the host does not match the URL, the error we see in the honeybadger report is thrown: "HTTP::StateError: Persistence is enabled for https://stacks.stanford.edu, but we got https://sul-stacks-stage.stanford.edu".

The reason for this error is that the configuration for staging in shared configs did not specify the host as being the staging host, even though the file_url property was set to use the staging URL.  The fix was to add the host to the shared config settings for the content staging server.

**Comment by hudajkhan** [comment]
I checked the timestamp on the shared config production.yml on content search stage, and the latest changes have been applied.  The search is working (although the query I entered took a long time but there were 952 hits)

**Comment by andrewjbtw** [comment]
Thank you! This works for me too. It does take longer to return results that I would expect from prod but I don't think that's related to this issue, so I think we can consider this done.
