### ISSUE TITLE
[sul-embed/stage] TypeError: this.player is undefined

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sul-embed#1968]
## Backtrace

```
  get captionTracks() {
>    const tracks = this.player.textTracks_?.tracks_
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49295/faults/102937867)

**Comment by mjgiarlo** [comment]
Race condition between `TranscriptController#load` and `TranscriptController#persistPlayer` ❓ 🤷‍♂

**Comment by hudajkhan** [comment]
Closed by #2025.

**Comment by hudajkhan** [comment]
These comments/explanation will also be duplicated on the pull request:

How this error occurs now:

- In the media_tag_controller file, when the videojs object is initialized, we listen for the "loadedmetadata" event.  At that point, we fire the vent for "media-loaded".
- In the media component html.erb file, the "media-loaded" event triggers the "persistPlayer" method in the transcript_controller javascript file, which saves the player object in "this.player"
- When the user clicks on the companion window, the transcript "load" method is triggered (you can see this connection again in the html erb file)
-  This error appears to be happening because the transcript controller "load" method can throw an error not recognizing "this.player" if the "loadedmetadata" event has not yet happened (and the resulting persistPlayer method has not been executed).
- Separately, based on analysis (noted below), the 'loadedmetadata' event happens before the tracks and cues are all necessarily available.

**Comment by hudajkhan** [comment]
In order to prevent this error (or any related to event timing), we propose the following mechanism:

- Decouple the transcript loading from the companion window click.
- Load the transcript when the tracks are available.  This event will be after "loadedmetadata" which would mean "this.player" should already be defined.

**Comment by hudajkhan** [comment]
Here are notes about the timings of events (also captured in the pull request):

I tried to capture the time (hour, minute, second, millisecond) when different events seem to be triggered/handled. Using the approach in the pull request, I captured the following:

- player loadedmetadata 17-1-52-994
- player loadeddata 17-1-52-995
- textTracks() addtrack 17-1-52-997
- player ready 17-1-52-998
- first track loadeddata 17-1-53-21

The first part identifies the object on which we are capturing the event, e.g. "player loadedmetadata" corresponds to "player.on('loadedmetadata')". For the player, the events that are triggered are 'loadedmetadata', followed by 'loadeddata', followed by 'ready'. We also tried to capture when 'addtrack' was triggered on the textTrack list (i.e. textTracks()) and when the 'loadeddata' method was triggered on the first track object. As can be seen, the first track loadeddata is the last to fire. Also importantly, I tried seeing when the tracks and cues were available for retrieval, and cue retrieval only works after the first track is loaded.

 I also tried out the following code setup:
const player = videojs(mediaTag.id, {}, () => { with the part in the {} representing the "ready" method for the player.

The timings captured were:

- player loadedmetadata 10-4-0-119
- player loadeddata 10-4-0-119
- player ready method 10-4-0-119
- player ready 10-4-0-123

The "ready" method is called after the "loadeddata" event, but before the "ready" event handler (i.e. player.on('ready').
I also checked to see which tracks/cues were available. When the ready method is called, "player.textTracks_.tracks_.length" returns 0. When the ready event handler is called (which happens later), this expression now returns 1 (in my example there was only one track) but the cues are still not available for processing as the code method to retrieve caption tracks still returns an empty array.

**Comment by hudajkhan** [comment]
Also for reference: https://github.com/videojs/video.js/issues/4468#issuecomment-349086527

**Comment by hudajkhan** [comment]
Also as reference: https://stackoverflow.com/questions/23067294/videojs-texttracks-cues-empty
