### ISSUE TITLE
Auto-expand the contents panel in the media viewer

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#2165]
### Requested behavior

To make it easier for users to find multiple resources within a single media item, default to showing the media viewer with the contents panel open when the viewer is first loaded.

<img width="1344" alt="Screenshot 2024-06-07 at 10 37 26 AM" src="https://github.com/sul-dlss/sul-embed/assets/8975583/aab088df-1705-466c-b401-d8c90f38524f">

We've received quite a bit of feedback from public services staff, curators, and the broader public that it is too difficult to find out when a media item contains multiple parts or components. 

### Current behavior

The viewer currently opens without showing the contents list and it takes multiple clicks + knowledge of where to click to find it.

**Comment by alundgard** [comment]
Rather than loading the viewer with the contents panel fully opened, it would be nice to show the panel opening animation upon page load. [Here is an example](https://uv-v3.netlify.app/#?c=&m=&s=&cv=1&manifest=https%3A%2F%2Fiiif.io%2Fapi%2Fcookbook%2Frecipe%2F0065-opera-multiple-canvases%2Fmanifest.json). This should help to indicate that the panel is also collapsible.
