### ISSUE TITLE
Handle objects without any exposed content files

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-embed#311]
e.g. http://purl.stanford.edu/bs380qs6014

**Comment by mejackreed** [comment]
@jvine ideas besides current behavior? 

http://embed.stanford.edu/iframe?url=http://purl.stanford.edu/bs380qs6014

**Comment by jvine** [comment]
@LynnMcRae what causes this to happen?

**Comment by cbeer** [comment]
Also: https://sul-purl-prod-b.stanford.edu/bb402bm5087

**Comment by LynnMcRae** [comment]
One cause which is of less concern is that PURLs get made for anything accessioned, which includes objects and metadata not ready for prime time (not ready for discovery).  Once released, I can see cases where files are available, but only on request, say, which you might want to list with labels as a sort of table of contents -- a file embed listing but not linking to the files. It makes less sense for image/media content to be published with no rendering ... except I guess for embargo situations (access restriction is temporary). And getting the thumb as fallback is nice in this case.

**Comment by hannahfrost** [comment]
I was just going to file an issue for this, but am glad to see it has already been observed as a problem. here is another example: http://searchworks-test.stanford.edu/preview/view/sz787pq4276

We can expect to see objects like this where the content is not published to PURL due to access restrictions; it has to be requested in person. Support for reading room-only access via PURL will help with some of these cases, but not all.

**Comment by mejackreed** [comment]
I'm curious, what should the embedded view of this then be? I think in a general case for files, images, geo, was what should the embed response be for content that is not available?

Not specifically asking @hannahfrost but I'm curious what @jvine and @ggeisler think as well. Is it incumbent upon the application embedding? Where does the business logic live to determine additional views?

**Comment by LynnMcRae** [comment]
Unlike ambiguous cases where there happens to be content published for shelved for reasons unrelated to dark, this case (https://purl.stanford.edu/sz787pq4276) is at least black and white.  There is an empty <contentMetadata> tag because no files is even published. 

One approach is to NOT publish the empty <contentMetadata> container making it appear to be just a citation only.  The object would then lack a content type, would not be expected to have an image manifest, etc.  But it would still have a PURL, so maybe that’s not a good combination (assuming we still want to offer the PURL that has the same limitation of nothing to show).  Seems like knowing the content type that is associated with the PURL is a good thing for other reasons, or just on principle … does it contribute to the icon shown as part of the searchworks display?

I’m assuming for now you are dealing with the empty contentMetadata as a reasonable given and working the downstream behavior. Let me know if changes to the source data in the public xml would help.

Lynn

**Comment by hannahfrost** [comment]
So if I understand correctly, a collection object's public XML should not contain <contentMetadata>. Correct? Is that was sul-embed looks for?

This item does have the element, and it's empty, which is made plain for all to see by the embed viewer:
https://purl.stanford.edu/ds247vz0452

This object was a very early Hydrus object. The newer collection objects do not contain <contentMetadata>

**Comment by LynnMcRae** [comment]
Hmmm references to XML tags in the text get swallowed somewhere, but I caught the meaning.  Sorry I completely missed this was a collection object! We can find and delete older empty contentMetadata datastreams. With your permission, I’ll clean this one up to verify.

Lynn

**Comment by hannahfrost** [comment]
(Sorry, forgot the markdown for displaying XML) Yes, please do find and delete older empty contentMetadata datastreams. Thanks, Lynn.

**Comment by hannahfrost** [comment]
Created another one of these cases today: https://purl.stanford.edu/mg662qq6088

@LynnMcRae - Can we circle back to this issue and determine if there are implicating factors beyond empty contentMD? Rosy suspects there is more to consider.

**Comment by LynnMcRae** [comment]
@hannahfrost did you use the Create Collection blue button in Argo for this, or did it come in via Hydrus?    We'll make sure the former does the right thing in new argo but may need for investigation otherwise.

**Comment by hannahfrost** [comment]
@LynnMcRae This particular item came in via Hydrus; Argo buttons had nothing to do with it. But I think the situation requires more explanation than this thread can support. We'll talk more at the meeting I scheduled for tomorrow morning.

**Comment by hannahfrost** [comment]
We are reaching closure with this ticket. There is nothing for sul-embed to do. We will make necessary changes in the objects' metadata so that they are properly displayed with sul-embed. Thanks, everyone!
