### ISSUE TITLE
Rosette location?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#416]
With the purl link removed from bottom right of the viewer, should we add the rosette back in? Change it's location? Or even have it in the viewer?

Do people besides those who work at SUL know what the rosette is?

@jvine @ggeisler @snydman

**Comment by ggeisler** [comment]
@mejackreed Was there not a plan to put the rosette in the upper left of the viewer, just before the title?

**Comment by mejackreed** [comment]
We had talked about that, but mocking it up it seems kind of strange to me. Also doesn't really add anything in my opinion... I'll post the mocks here.

**Comment by mejackreed** [comment]
Some alternatives I have created. I think the variability is too strange with the header and adding the rosette there.... Thoughts?

![rosette placement alts](https://cloud.githubusercontent.com/assets/1656824/9890865/88e651ea-5bb7-11e5-9602-79db4b2eed5d.png)

**Comment by ggeisler** [comment]
Thanks for the examples. I understand your concerns about it, though I also like the idea of having the rosette somewhere for branding purposes. Not really my call, though, so maybe we can just discuss with @jvine and maybe @snydman in person sometime.

**Comment by jvine** [comment]
Could it be the same size (smaller, top-aligned) regardless of the presence/absence of the title? And the same left margin as the info button on the bottom toolbar. 

![rosette alt](https://cloud.githubusercontent.com/assets/6945691/9943304/766e808a-5d35-11e5-992a-28776400d6b8.png)

Meh. What do you think? (I also reduced the vertical space between the heading and the number of items.)

Whether people will know what it is... we will be helping to increase its recognizability, no?

**Comment by ggeisler** [comment]
I agree the logo should be a consistent size. Personally I'd left-align it with the left edge of the card in the main content area, or at least move it right and down a bit so it isn't so tight to the corner. It could even be a bit smaller, so that its height is similar to the height of the title (that way, when there is no title, the logo is only a little taller than the item text).

I'm not clear if the left-alignment in @mejackreed's examples here are intended to be accurate though? Looking at the sandbox the bottom icons are not as far left as they are in these examples. The sandbox versions seem better to me, in terms of alignment.

**Comment by jvine** [comment]
Yeah, align w card makes more sense. :+1: to everything.

**Comment by mejackreed** [comment]
Just for my 2 cents.. the card alignment only takes place on file viewer... everything else will not have that alignment (if that even matters). I'll work this up
