### ISSUE TITLE
Embargoed images show a blank viewer

### ISSUE THREAD

**Issue by rosy1280** [sul-dlss/sul-embed#464]
When attempting to view an embargoed object with the content type = image, I receive the image viewer with no image and no information regarding the embargo.  Its unclear how many other content type (book, media, maps, etc.) this effects.

Example from test: https://purl-test.stanford.edu/gt473qx0315

**Comment by mejackreed** [comment]
I think we should put our heads together with @cbeer on how this should be resolved. Purl is returning a valid manifest.json with references to iiif resources. Should embed handle this? Purl? Both? Stacks seems to have the correct access controls.

**Comment by cbeer** [comment]
cc @LynnMcRae too. I'm not sure of our intention for a IIIF manifest is in this case.

**Comment by LynnMcRae** [comment]
purl-test and vpn not working for me at the moment so I can't check details of the object.  The question is about the rights per se (world, stanford, none) whether they are that way from embargo or not.   I think we handle stanford-only images, so I assume this is a "dark" image in a non-dark object (a fully dark object would not have a purl). The owner would have to want to reveal the existence/presence of the image without letting the user see the image.  This scenario sort of makes sense with file content because we can list a file name a la table-of-contents but just not make it a link. But images? Media?

Actually, embargo does play a role here, because the user may have simply published the images in anticipation of the lifted embargo. Is the file in question both shelved and published? We could perhaps legitimately show the thumb and nothing else though we'd have to float that in case there are issues with revealing any information (e.g., a digitized letter). If it's published a not shelved? I think that's a non-use case because I can't see the point of that.

As I write this, I wonder if we should ignore publish=yes for image or media content that is dark and omit it from the purl.

**Comment by LynnMcRae** [comment]
I see now that the image in the example is Stanford-only.  I thought that was where we showed a thumbnail and didn't allow any further views.  Here is an example in production purl where access=read is none (dark content) so we show only a thumbnail and nothing more -- http://purl.stanford.edu/bb020ng8351-- so something like that is what we'd expect from purl-test? There is the separate question about whether the embed accommodates the message re "Access restricted until ..." when there is an embargo.

**Comment by rosy1280** [comment]
The images weren't showing when a user was web-authed because of file level permission issues.  That has been fixed.

When not web-authed, a user still sees a blank sul-embed image viewer with no information about about the embargo.

**Comment by aeschylus** [comment]
I still just get "request failed" when requesting https://purl-test.stanford.edu/gt473qx0315

**Comment by rosy1280** [comment]
@aeschylus are you webauthed?  if not that would explain it...

**Comment by mejackreed** [comment]
@aeschylus what environment are you doing this?

**Comment by mejackreed** [comment]
This is resolved w/ M3
