### ISSUE TITLE
Multi-image scrollbar wonkiness

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-embed#478]
- [ ] I expected to be able to scroll the multi-image area using standard scrolling controls (e.g. 2 finger swipes for me, but probably other conventions too)
- [ ] I can't drag the scrollbar from the far-left position on records with lots of pages, e.g. http://embed-prod-b.stanford.edu/iframe?url=https://purl.stanford.edu/mv660ws7416
- [ ] when I drag the scrollbar, I expected the contents of the pane to scroll with me, so I know when to stop scrolling.
- [ ] Clicking `•••` to minimize the scrollbar pane was unintuitive. I kept trying to click + drag to resize.

**Comment by mejackreed** [comment]
Thanks for reporting this. One decision that was made (it may not be the correct one) was two use this view much more of a local navigation rather than a global one. Where when I use the scroll bar, it is actually changing the page to be viewed. It's great to hear feedback about what your initial expectation was wrt the scroll bar.

**Comment by mejackreed** [comment]
Resolved in m3
