### ISSUE TITLE
Evaluate a media viewer for phase 1

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#511]
* HTML5 (plain)
* jwPlayer
* MediaElement.js
* AblePlayer
* OzPlayer
* video.js

**Comment by jkeck** [comment]
This ticket is very large and doesn't necessarily lend itself to estimation.  This is more of an exploratory ticket that we may want to consider breaking down.  Once somebody is ready to look into this, let's evaluate and breakdown this ticket into its realistic components for estimation.

(barring that, I would suggest that 2 people tackle this as a day+ long project and present findings back to the team)

**Comment by aeschylus** [comment]
Create.js is another option. MediaElement is probably the quickest and most light-weight, with some flexibility. 

The plain html5 media element apis are surprisingly consistently-supported and pleasant to work with, and gives you much better decoupling/styling ability, since you can create pretty much anything that's asked for.

**Comment by hannahfrost** [comment]
MediaElement.js is what is used in Avalon. I think Chris Colvard knows it pretty well.

**Comment by ndushay** [comment]
Main concerns are accessibility and the controls.  There are 2-3 relevant JIRA tickets.  Also would like link to Avalon docs about criteria?

**Comment by ndushay** [comment]
closing this;  we've chosen our media viewer(s) for phase 1.
