### ISSUE TITLE
Implement prototype dash player to allow playback in all browsers

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#545]
This allows video display support for browsers other than safari and ios.

**Comment by jkeck** [comment]
I'm going to table this for the day (been spinning my wheels trying to find a good first-pass).  Each of the simple implementations has some caveats or some additional work/investigation that would be required to get it working. 

* Dash.js - Safari support seems spotty
  * Did not appear to handle deep linked manifests/redirects in Safari well.
  * Still seemed to be buggy when pointing directly to wowza in Safari.
  * Would like to try and force Safari to use HLS instead of DASH since it is natively supported.
* MediaElement - Seems to require Flash on browsers like chrome for DASH/HLS.
  * Also did not appear to handle deep linked manfests/redirects well (on any browser).
  * Would require some (relatively simple) stacks changes to support flash (e.g. `crossdomain.xml`)
* Video.js - Implements Dash.js for DASH / Has a contributed HLS plugin
  * Since it implements Dash.js for DASH, a simplification was just to implement Dash.js (we need to address other Dash.js issues).
