### ISSUE TITLE
restricted images not showing login link

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#591]
it worked yesterday (see #582 images), but can't get it working locally or on purl-test today, even backing up to an earlier commit.

**Comment by ndushay** [comment]
this may be due to using IIIF viewer ...

**Comment by ndushay** [comment]
production image with restriction (object level):  https://purl.stanford.edu/bh017xy6150

test image with restriction (object level):  http://purl-test.stanford.edu/rj657cr0908

**Comment by jmartin-sul** [comment]
what i've found so far:
* embed determines whether it should show the login link based on a call to `/image/iiif/token.js` on stacks.  if it gets a token back, it sees the user as auth'ed, and doesn't present the link.  otherwise, it presents the link.
* in my testing, even if i wasn't webauth'ed, sul-embed would always get a token back from stacks, and indeed, when i hit `https://sul-stacks-test.stanford.edu/image/iiif/token.js/image/iiif/token.js` directly, i always got a token back in the json response (regardless of my webauth status).

a few notable pieces of code:
* stacks application controller had [this change](https://github.com/sul-dlss/digital_stacks_rails/commit/c2666bfd651ca45c0cb7684abd15b38eb77f3809#diff-55c5b7aecfb519d0e4880eaf2788eb6e), which (AFAICT) results in `ApplicationController#current_user` never returning a `nil`, whereas `current_user` used to be able to return `nil`.
* the iiif bearer token only gets written to the cookie if stacks sees the user as a webauth user ([see iiif_token_controller.rb](https://github.com/sul-dlss/digital_stacks_rails/blob/master/app/controllers/iiif_token_controller.rb#L48)).
* however, `IiifTokenController#create` returns the json with the bearer token as long as `current_user` is not `nil`.  but now it seems that `ApplicationController#current_user` will never return `nil`, and so the `token.js` call will always return a valid `accessToken`.

it seems to me that the solution is to make the check in `IiifTokenController#create` more strict, but exactly how strict, i'm not sure.  input from @jkeck or @ndushay or someone who's worked more deeply on stacks auth stuff recently?

(thanks to @peetucket for the second set of eyes in tracing through the stacks code)
