### ISSUE TITLE
Full-screen button doesn't work on embedded viewers in library website

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#596]
Examples: 
http://library.stanford.edu/blogs/digital-library-blog/2016/06/hacking-david-rumsey-center-part-2
(down at the very bottom)

https://library.stanford.edu/blogs/digital-library-blog/2015/11/what-you-need-know-about-redesigned-sdr-purl-page

**Comment by jkeck** [comment]
The embed code that is generated by SUL-Embed includes the `allowfullscreen` attribute on the `<iframe>` tag that allows content in the iframe to show use fullscreen features in the page that embeds the iframe.  Whoever generated the embed code either did it by hand, or decided to remove the `allowfullscreen` attribute.

The authors of these blog posts will need to retain that attribute on the iframe in order to allow fullscreen behavior.

**Comment by jvine** [comment]
If the “allowfullscreen” attribute is not present in the iframe tag, should the embed not maybe perhaps suppress the fullscreen button?


On Jun 16, 2016, at 3:18 AM, Jessie Keck <notifications@github.com<mailto:notifications@github.com>> wrote:


The embed code that is generated by SUL-Embed includes the allowfullscreen attribute on the <iframe> tag that allows content in the iframe to show use fullscreen features in the page that embeds the iframe. Whoever generated the embed code either did it by hand, or decided to remove the allowfullscreen attribute.

The authors of these blog posts will need to retain that attribute on the iframe in order to allow fullscreen behavior.

**Comment by jkeck** [comment]
It is not possible for us to know the attributes of the embedding iframe from within the embed.
