### ISSUE TITLE
Add drag and drop IIIF icon to info panel

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#622]
See #566 for the code relating to the drag and drop link. 

Panel looks like this:

![screen shot 2016-06-01 at 4 26 43 pm](https://cloud.githubusercontent.com/assets/6945691/15729126/4a233b40-2816-11e6-997e-8aec3a3f4f93.png)

- IIIF feature and PURL are in separate dt/dd pairs 
- dt for PURL changes to "Citation URL"
- dt for draggable icon is "International Image Interoperability Framework"
- icon is about 25px wide w 5px right margin
- icon has "grab" cursor
- instruction text is "Drag icon to open this image/set in a IIIF viewer."
 - generic text is okay, but if possible, it would be better to check to see if there is 1 image, or multiple images, and adjust the text accordingly. 
 - Drag icon to open **this image** in a IIIF viewer.
 - Drag icon to open **these images** in a IIIF viewer.
- text colour for instruction is dimgrey 
- link on "IIIF viewer" points to http://library.stanford.edu/projects/international-image-interoperability-framework

**Comment by peetucket** [comment]
Timebox this before holding up release

**Comment by snydman** [comment]
Upon testing this it appears that I need to try this twice for it to work.  See the screen recording to see what I mean.  I try to do the drag and drop once, and nothing happens.  I go back to PURL and try a second time and it is successful.  It doesn't appear to be related to our Mirador installation since I get the same behavior with the Harvard Mirador instance.  I also tested the Digital Bodleian drag and drop and it seems to work on the first try.  

https://stanford.box.com/s/ek7k7q02u7jrh52kdzt90wvdiatw5k6y

**Comment by jkeck** [comment]
That is odd.  This works simply aa link w/ a URL parameter to the manifest.  I noticed that we had a double slash in our URLs (a configuration anomaly on this particular embed server) which was causing the issue.  It looks like it's working 👌  for me now, please give it a look and if it looks good, go ahead and re-close this ticket.

I wonder if that's something that we should report upstream?  The URL https://purl.stanford.edu//fw090jw3474/iiif/manifest.json resolves to the manifest URL just fine, so I don't see why the IIIF viewer would intentionally cause a URL like that to have to be dropped twice in-order to work.  Clearly it is able to parse the manifest URL.
