### ISSUE TITLE
Responsiveness issue with footer toolbar

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#675]
This only happens when I manually adjust the desktop browser width - not when it's actually on a mobile device. At a certain point the iframe adds a horizontal scrollbar that obscures part of the footer. And then when I scroll right, the footer ends before the iframe does. 

![screen shot 2016-08-26 at 11 30 53 am](https://cloud.githubusercontent.com/assets/6945691/18016330/ad127a74-6b80-11e6-92cc-a63d7363dd6b.png)
![screen shot 2016-08-26 at 11 30 59 am](https://cloud.githubusercontent.com/assets/6945691/18016333/af51f918-6b80-11e6-9d95-daeb313e19df.png)

**Comment by jkeck** [comment]
After talking this over w/ @jvine this afternoon, I believe the best way to solve this issue is to do the following:

1. Remove icon behind restricted message. (It has been causing some display issues)
1. Make `<audio>`/`<video>` tag `display: none` until we initialize the videoJS player. (This removes the browsers default HTML5 styles element, which can be inconsistent across browsers as well as adds additional elements in the tab order)

**Comment by jkeck** [comment]
Should be fixed with #664.
