### ISSUE TITLE
Thumb/square image in slider can be too big to display for no-download image

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/sul-embed#699]
By "too big" I don't mean huge, but rather a thumb-related calculation comes up with a >400 pixel edge that fails to load in the slider for an image that is no-download (limited to 400px on the long edge for display).  Example: https://purl.stanford.edu/kf903ds6573, see second square in the slider.

From Slack discussions with Jessie:

This code - https://github.com/sul-dlss/sul-embed/blob/4a0581ac21588eb65b582d50105fea4267b94809/app/assets/javascripts/modules/image_x_viewer.js#L464-L465

... calculates this for the second image which rounds up to 417: Math.ceil(100 \* (17441 / 8370) \* 2)

...and asks for the image thusly: https://stacks.stanford.edu/image/iiif/kf903ds6573%2Fkf903ds6573_00_0002/full/417,/0/default.jpg

Note the URL works if you change the number 400: 
https://stacks.stanford.edu/image/iiif/kf903ds6573%2Fkf903ds6573_00_0002/full/400,/0/default.jpg

Ironically this is being used as the base image from which a 75px high image is derived for the slider.

**Comment by cbeer** [comment]
Could the slider use e.g. https://stacks.stanford.edu/image/iiif/kf903ds6573%2Fkf903ds6573_00_0002/full/!400,400/0/default.jpg

**Comment by jkeck** [comment]
Yeah, I'm curious why we need to calculate this image size at all. Was hoping @mejackreed or @aeschylus might be able to comment on if there is some behavior we're trying to achieve by calculating that image size dynamically.

**Comment by mejackreed** [comment]
Some background:

The tile slider will request an image thumb, consistent with the same size that is requested by OSD for the overview display. This is so that we aren't requesting multiple images just to display a thumb and is using a [IIIF canonical URL](http://iiif.io/api/image/2.1/#canonical-uri-syntax).

The size display here is important and relates to the size of the thumbslider area which has a set height.

Using the `/!400,400` might work in some cases as a work around, but if the image is very wide (>`n` x the height) we will run into a sizing problem as the image may not be tall enough (could be stretched to be distorted) and anything over another value `r`, will look pixelated on a retina display.

```
n = 2.667
r = 5.333
```

I hope this helps discuss the problem some more. I think this only happens on images that have a `width` that is`n` times greater than their `height` and are restricted to no download.

**Comment by LynnMcRae** [comment]
Our policy regarding thumbs is that we can consider anything up to 400px on the long edge as public metadata,and it happens that no-download is the only scenario where we are limiting the user to that size.  Pushing that limit would be iffy, though this is just a mild case of extreme proportions ... what would a legal thumb be for a long wide scroll for instance.  What we want I think is the ability to present a useful thumb that might be longer/wider in the absence of restrictions, but accept what we get for the 400px ceiling? Or some flexibility in the policy for thumbs of unusual proportions? Or is the slider case in fact easier given it's a square, not a thumb, and is gonna chop the image anyway?

**Comment by mejackreed** [comment]
The slider case is a thumb (not a square). In this case (and other cases where proportions are extreme) a 400 on long edge is not a great representation (but what is :) ).

**Comment by LynnMcRae** [comment]
I must have gotten the notion of a square from an example like this -- https://purl-test.stanford.edu/pd507wn8117 -- do we know the difference between that and something like https://purl-test.stanford.edu/rc002dt8345? 

I wonder if we could make a case that 400px on the long edge is really saying a max of 160000 units of information and could allow any dimensions whose product doesn't exceed that?  A nice 4x6 image would be roughly 320x500. Just spitballing here; that could be too radical.

**Comment by mejackreed** [comment]
Resolved w/ m3
