### ISSUE TITLE
`100%` or `100%25` as a width parameter no longer forces embed to 100% width

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#716]
Functional change in sul-embed, that when using `100%25` (100% html encoded) embed no longer forces the width to 100%.

Reported by @abrin in relation to some issues they are having with the Rumsey map room.

Example: http://www.davidrumsey.com/luna/stamen.jsp?pid=wv304jy9677

**Comment by jkeck** [comment]
@mejackreed thanks for reporting this.

Interesting, I wasn't aware that anybody was passing through things like percentages.  This has changed because I realized, that in certain cases, we were blindly placing the user's parameter directly into the markup (which as you know can be hugely problematic).  So, I think this _happened_ to work because it was piggybacking on a vulnerability in our codebase (whoops).

You'll notice in the [oEmbed spec](http://oembed.com/) that `maxwidth` and `maxheight` are always an integer.  So, we now call `to_i` on the param to ensure that we're getting a sane value before putting it into the viewer markup.  This is causing `100% or `100%25` to get turned into `100`.

```
>> '100%'.to_i
=> 100
>> '100%25'.to_i
=> 100
```

But, fear not! 100% width is obviously a primary use case of SUL Embed.  What we've done now is allow the embed content to flow to 100% width whenever a `maxwidth` is not specified.  So in order for @abrin to get 100% width on SUL Embed, they simply need to not provide any `maxwidth` parameter and everything should work out fine ([see PURL](https://purl.stanford.edu/wv304jy9677))

**Comment by jkeck** [comment]
Also, just curious if there is a particular reason why these reports are filtering through a single dev?

I worry that is not a scalable solution and could potentially delay our ability to respond in as timely of a manner as we could if the reports were going through the proper channels (although I trust @mejackreed will always disseminate the information properly and quickly).

**Comment by abrin** [comment]
@jkeck it's more a matter of I wasn't aware of the GitHub repo and asked @mejackreed for help and to point me at the issue tracker.  He was kind enough to just create the ticket.  

Removing the parameters in the URL appeared to have worked.

thanks!

**Comment by jkeck** [comment]
Wonderful @abrin.  Glad to see that it worked out.

Please feel free to submit feedback, bugs, and feature requests here in the future!
