### ISSUE TITLE
related to #716 getting embed to fill screen

### ISSUE THREAD

**Issue by abrin** [sul-dlss/sul-embed#718]
Hi, related to  issue #716, I didn't initially notice it (wrong shape image) but when you use the embed with an undefined maxwidth and  maxheight, it no longer fills the screen:

<img width="1336" alt="screen shot 2016-09-22 at 7 19 30 pm" src="https://cloud.githubusercontent.com/assets/192686/18772185/b1b9f60e-80f9-11e6-9c89-3d6c781cd31d.png">

The old behavior, when you could specify a maxheight=100% and maxwidth=100% would make the image in the embed almost as wide as the screen and would extend the height to the screen height, vertically centering (if I remember) the image.

thanks

**Comment by jkeck** [comment]
Ah, okay, I see what is happening.  Let me see if I can explain.

As with the percentage width, the percentage height happened to work because we were erroneously allowing any arbitrary string to come through the `maxheight` and `maxwidth` parameters and injecting it into the markup (which could have potentially been used for nefarious purposes).  We had to stop doing that for security purposes.

Would you be able to provide the previous URL you were using to fetch the JSON at the top of http://www.davidrumsey.com/luna/stamen.jsp?pid=wv304jy9677 ?

I would like to pull up the code as it was and see how the 100% height was propagating through the markup and see if there is anything we can do to support a 100% page-height iframe.

**Comment by abrin** [comment]
Hi Jessie,
 I totally get tainting and validating the input. Here’s the original version of what we were requesting. If helpful, here’s the full example of the stamen.jsp … even if you’re not 100% fluent in java/jsp, this is the line you want:

        URL oracle = new URL("http://embed.stanford.edu/embed?url=https://purl.stanford.edu/"+param+"&hide_search=true&hide_embed=true&maxwidth=100%25&maxHeight=100%25”);


  For more detail — this is being used in the new Stanford Map Library to show the maps full-screen on an iPad Pro. 




thanks,

adam

**Comment by abrin** [comment]
Hi Jessie,
  Sorry to bother. There's a big opening in the Map Library on the 4th of October, is it possible to have a resolution by then, or is there something you can suggest to mitigate the issue from the embed end.  With how this works, one of the challenges is that I don't have access to window size at the point of the call, is there a JS Method I can call to resize the widget post-render?

thanks,

adam

**Comment by jkeck** [comment]
There unfortunately isn't a resize API that would allow you to do that with the embed viewer.

I'll take a look at this very soon.  We have a production release to Embed happening today, and once we've done that I can spend some more time looking at this.

**Comment by jkeck** [comment]
@abrin, okay, so I think I have a handle on how this was working before.  As I mentioned previously, we are now shipping an iframe as the HTML.  This means that the CSS that you're applying to the contents of the viewer are no longer being applied (you cannot style content within an iframe from the parent).  This also may be affecting some of the javascript that was intended to manipulate the viewer content, which I think may also not work (but YMMV).

This is necessary for various reasons, but one of them is also to constrain customizations to those that we provide (i.e. not being able to hide mandatory license or attribution information, etc).  We also need to constrain the origin that is executing the javascript to the embed service to facilitate some new features that were just released.

That being said, I want to provide a way to enable a full height viewer experience you previously had (at least for the image viewer).  I propose that we add a url parameter to the embed service.  I also suggest that we not advertise this customization parameter as I don't believe this is a common use case.  This url parameter will be `fullheight=true` (and `maxheight` should be omitted).  You'll want to change your css to from forcing the sul-embed classes to 100% height to forcing the resulting iframe to 100% height (use `!important` as you already are since there will be a height set by the iframe element).

You can see the result of that in the screenshots below from a browser and an iPhone.

If this looks agreeable to you, I'll work on getting a PR submitted, reviewed, and deployed to production before the Oct. 4th opening.

## Browser
<img width="1278" alt="full-screen-desktop" src="https://cloud.githubusercontent.com/assets/96776/18977709/97fc1f30-8671-11e6-9213-920571a9e4bf.png">

## iPhone
![full-screen-iphone](https://cloud.githubusercontent.com/assets/96776/18977708/97f8001c-8671-11e6-9f98-83b72c360609.PNG)

**Comment by abrin** [comment]
Hi Jessie,
  I think this would work nicely.  We really appreciate it. I may have to mess with the CSS a bit to fix things, but the LUNA embed also uses an iframe and I’ve successfully been able to work around some of it’s limitations. It might also make sense to remove the full-screen icon with the full-screen option enabled.

thanks,

adam

**Comment by abrin** [comment]
can you let me know when this is deployed?  I added the fullheight=true, removed the maxHeight and maxWidth  parameters but don’t see the .sul-embed-fullheight class and it’s still creating an iframe of height 513. ( http://www.davidrumsey.com/luna/stamen.jsp?pid=wv304jy9677 ).

thanks,

adam

**Comment by jkeck** [comment]
@abrin this has now been deployed to production.

**Comment by abrin** [comment]
thanks, I’ll pass it on the library folks.
