### ISSUE TITLE
UV: Browser incompatibility with PDF rendering

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#768]
http://universalviewer.io/examples/#?c=0&m=0&s=0&cv=0&manifest=http%3A%2F%2Fdms-data.stanford.edu%2Fdata%2Fmanifests%2Fv3test%2Fbh502xm3351%2Fmanifest.json

Works in Safari, but not Firefox or Chrome

**Comment by cbeer** [comment]
From chatter in the UV slack and a quick test, it seems like the problem is we serve up files with `Content-Disposition: attachment` to trigger a download behavior (https://github.com/sul-dlss/stacks/blob/master/app/controllers/file_controller.rb#L15), but the chrome embed needs it to be `Content-Disposition: inline`.

I don't think we want to unconditionally switch to `inline` because some users probably expect our download links to trigger a file download.

We could decide to update our front-ends to use the `<a download>` attribute to force downloads from the UI (so we could switch to using `inline`). Alternatively, figure out some heuristic to detect UV and only use `inline` for it. Or, figure out if there's a workaround for chrome etc (although cursory googling comes up empty..).
