### ISSUE TITLE
Repeated login prompts on Stanford only multi-image object in UV

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/sul-embed#802]
https://sul-purl-uat.stanford.edu/fr352bj3947 

It appears authorization is trying to happen on every resource instead of the object. Possibly related, but I'm also getting a 'message unhandled after 5000ms, rejecting' error shortly after navigating around the object.

**Comment by mejackreed** [comment]
Leaving some reference here for more work on Monday. (So I don't lose my place)

I'm wondering if this is because of the way we are passing in the bearer token from an authentication request.

Our current response does something like this:

```json
{
  "accessToken":"token=\"abcdefghijklmnop\"",
  "tokenType":"Bearer",
  "expiresIn":3600,
  "messageId":"1503090359833"
}
```
The UV examples I've seen don't have the `token="` prefix and the token is just the token. I'm unsure of why we need to do this and there seems to need further investigation.

On a successful login, this will return ok.. but on successive auth attempts (for other info.json or images) the Authorization header is present with bearer token but it is unable to auth from Stacks

```
Authorization: Bearer token="abcdefghijklmnop"
```

**Comment by mejackreed** [comment]
Based off of this comment, Rails appears to handle this type of token. https://stackoverflow.com/a/44914747 I'm wondering if UV struggles with it and IIIF auth doesn't expect it.
