### ISSUE TITLE
Download link text is confusing

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#807]
Testing : https://sul-purl-uat.stanford.edu/bc421tk1152 in Chrome on Mac

The download link text is confusing.  Maybe "Current View" can be changed to something like "Zoomed region only" or something.  Was also a little confused by two links that said "Whole Image" but with different sizes.  

Interested in @jvine and @ggeisler thoughts on this.  

![image](https://user-images.githubusercontent.com/3279382/29472184-b7250e82-8407-11e7-8849-1833ac384df6.png)

**Comment by ggeisler** [comment]
@jvine might have more thoughts based on her past experience thinking about downloads for SUL-Embed, but @snydman I like your suggestion of "Zoomed region only" except maybe "Zoomed region" is enough to be clear? Here's an edit that also adds a semicolon after the type of download:

![_ma_pickaninny_babe_____stanford_digital_repository](https://user-images.githubusercontent.com/101482/29472894-70ce823a-840a-11e7-8774-b631bdda15a1.png)

This also groups the two download versions together, rather than having the zoom version in between them. Not sure how feasible that might be. 

I had to widen the modal container slightly to keep the options on a single line.

**Comment by jvine** [comment]
I like all @ggeisler's changes. "Zoomed region" seems clear; grouping the whole image options makes them easier to compare.
