### ISSUE TITLE
Loading an item in exhibits, will raise an unable to authenticate error on load

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul-embed#827]
### Expected behavior
Should not present a user with a popup on default
### Actual behavior
<img width="666" alt="screen shot 2017-09-21 at 3 35 16 pm" src="https://user-images.githubusercontent.com/1656824/30721785-89e1db76-9ee2-11e7-8be4-892e4d6f1a36.png">

### Steps to reproduce the behavior
1. visit https://exhibits.stanford.edu/ua-maps-drawings/catalog/yd068bc5869
### Browser / Environment
Chrome / macOS

**Comment by mejackreed** [comment]
`No TileSource was able to open undefined Object` reporting in OSD.. but strange not in other contexts. cc @aeschylus

**Comment by aeschylus** [comment]
Refreshing the page after seeing this, even without logging in, causes the entire viewer to be unclickable (no buttons or zooming work).

Currently comparing the initialisation code between contexts.

The "no Tilesource was able..." nonsense is odd because the manifests are the same regardless of the embedding contexts, so OSD should have the same reaction to their tilesource JSON.
