### ISSUE TITLE
URL encoding error in CommonViewer

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/sul-embed#859]
See https://app.honeybadger.io/projects/49295/faults/34491836 (HB's GH integration isn't working for me for some reason).

**Comment by jcoyne** [comment]
This is due to files that have unescaped `[` or `]` characters.

See these examples: 
https://purl.stanford.edu/pk521wd7589.xml
https://purl.stanford.edu/sn866kq8471.xml
https://purl.stanford.edu/mk114rp1100.xml (though this one has a different path)
https://purl.stanford.edu/hr313dw9240.xml
https://purl.stanford.edu/tm772zz7352.xml

**Comment by mejackreed** [comment]
There was a previous issue that was very similar (for history) https://github.com/sul-dlss/sul-embed/issues/746

**Comment by mejackreed** [comment]
Resolved with #863 and #865
