### ISSUE TITLE
Add Alternate viewer section to Share dialog

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#989]
Part of #986.

The Alternate viewer section is intended to look like this:

<img width="617" alt="Screen Shot 2019-05-16 at 5 33 50 PM" src="https://user-images.githubusercontent.com/101482/57895580-299d8400-7801-11e9-89d7-8ba482229919.png">

- [x] Add IIIF icon (should be one in SW repo?) with the drag and drop behavior as in SW and exhibits like Parker.
- [x] Add text: `Drag & drop this icon to any IIIF viewer. [What is IIIF?]` in `body1` typography, with the "What is IIIF?" part linked to https://library.stanford.edu/projects/international-image-interoperability-framework/viewers

**Comment by jkeck** [comment]
@ggeisler Since this is a plugin that will generally be available to others (AFAIU) I've made the `What Is` link a configurable option (so it won't show up if the URL isn't configured).

I am also making that URL the base URL of the image link so that if you click on it instead of drag you will go to that page (as I believe this is what we do elsewhere).

If there is no configured URL, the click on the icon will just take you to the manifest URL itself (not sure what else we would want to do here).

**Comment by ggeisler** [comment]
Good thinking, those sound like the right decisions to me 👍  Sorry I didn't think about the implications for other implementors, and what to do if they don't follow the expected pattern.
