### ISSUE TITLE
Handle the case where zoom past 100% occurs (and is not desired)

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/sul-embed#996]
### Expected behavior

Expected behavior is that maximum zoom level = 100% of image size.

### Actual behavior

Zooming past 100% occurs. Per @mejackreed : ` .. looks like OSD requests a version of the image and then is scaling it down for viewing` and `I think its a combination of the “lower” resolution quality of the image, and how OSD interprets “sizes” to render. Kind of hits a strange edge case border it seems like`

### Steps to reproduce the behavior

For a given object (https://purl.stanford.edu/bb014vg2844 for instance), zoom in as far as possible or make a specific URL request like https://stacks.stanford.edu/image/iiif/hg676jb4964%2F0380_796-44/0,1357,1357,1357/2714,/0/default.jpg . This will allow zooming past 100% resolution.

Astrid Smith (DPG) reports user complaints due to this.

**Comment by cbeer** [comment]
Is this in any particular browser? I'm not seeing the described in any browser I tested.

**Comment by blalbrit** [comment]
I'll ask Astrid to weigh in on the report from the user she got. @mejackreed - any thoughts?

**Comment by mejackreed** [comment]
I'm seeing the issue in Chrome where the image https://stacks.stanford.edu/image/iiif/bb014vg2844%252Fbb014vg2844/0,0,3600,2400/900,/0/default.jpg is requested and displayed by OSD. This image appears to appear from some resolution reduction where perhaps the scaling on the image server reduces quality and with the smaller image it appears more degraded.

^^ What I think is happening. A higher resolution image doesn't get this effect as its not perceivable

**Comment by AstridJS** [comment]
Hi @cheungd01 
This is the open ticket where we are addressing the behavior we discussed earlier. Thank you, @blalbrit, for posting it.

All, the feedback is very general -- basically the effect is that it looks like images become fuzzy at the highest zoom, which we thought could be a product of overshooting 100% but seems like it may be something else causing the same visual problem?  Let me know if you have any questions, otherwise we'll watch the ticket for updates as they come. Thank you! 

Best,
Astrid

**Comment by mejackreed** [comment]
@AstridJS is this still happening with the new viewer?
